version: '3.0'

expectations:
  population_size: 1000

actions:
  split_codelist:
    run: r:latest analysis/00_trim_snomed_codelist.r
    outputs:
      highly_sensitive:
        data: codelists/ethnicity_*.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output --output-format feather
    needs: [split_codelist]
    outputs:
      highly_sensitive:
        cohort: output/data/input.feather

  generate_dataset_report:
    run: >
      dataset-report:v0.0.9
        --input-files output/data/input.feather
        --output-dir output/data
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        dataset_report: output/data/input.html

  execute_simple_validation_analyses:
    run: python:latest python analysis/simple_validation_script.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/simplified_output/5_group/tables/*.csv
        # figures: output/simplified_output/5_group/figures/*.png
