### CTV3, PRIMIS, SNOMED analysis

version: '3.0'

expectations:
  population_size: 1000

actions:
  split_codelist:
    run: r:latest analysis/00_trim_snomed_codelist.r
    outputs:
      highly_sensitive:
        data: codelists/ethnicity_*.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-file output/extract/input.feather --output-format feather
    needs: [split_codelist]
    outputs:
      highly_sensitive:
        cohort: output/extract/input.feather

  generate_dataset_report:
    run: >
      dataset-report:v0.0.9
        --input-files output/extract/input.feather
        --output-dir output/extract
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        dataset_report: output/extract/input.html

  execute_simple_validation_analyses:
    run: python:latest python analysis/simple_validation_script.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/simplified_output/5_group/tables/*.csv

  execute_simple_validation_analyses_16:
    run: python:latest python analysis/simple_validation_script_16.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/simplified_output/16_group/tables/simpl*.csv

  combine_ons:
    run: r:latest analysis/combine_ons.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        data: output/ons/ethnic_group*.csv
        data2: output/ons/ethnic_group_NA*.csv
        data3: output/ons/data_check*.csv

  ons_plot:
    run: r:latest analysis/ons_plots.R
    needs: [combine_ons]
    outputs:
      moderately_sensitive:
        plot_na: output/ons/na_removed/ethnicity_*.png


## Only to be run locally
  generate_report:
    run: python:latest jupyter nbconvert /workspace/notebooks_jupyter/draft_report_ethnicity.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [execute_simple_validation_analyses,execute_simple_validation_analyses_16]
    outputs:
      moderately_sensitive:
        notebook: output/draft_report_ethnicity.html

  local_simple_run:
    run: python:latest python analysis/local_simple_run.py
    outputs:
      moderately_sensitive: 
        tables: output/from_jobserver/release_2022_11_18/made_locally/*.csv

######## SUS
  execute_simple_validation_analyses_sus:
    run: python:latest python analysis/sus/simple_validation_script_sus.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/sus/simplified_output/5_group/tables/*.csv
#        figures: output/sus/simplified_output/5_group/figures/*.png

  execute_simple_validation_analyses_16_sus:
    run: python:latest python analysis/sus/simple_validation_script_16_sus.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/sus/simplified_output/16_group/tables/simpl*.csv

#   combine_ons:
#     run: r:latest analysis/combine_ons.R
#     needs: [generate_study_population]
#     outputs:
#       moderately_sensitive:
#         data: output/ons/ethnic_group*.csv
#         data2: output/ons/ethnic_group_NA*.csv
#         data3: output/ons/data_check*.csv

#   ons_plot:
#     run: r:latest analysis/ons_plots.R
#     needs: [combine_ons]
#     outputs:
#       moderately_sensitive:
#         plot_na: output/ons/na_removed/ethnicity_*.png

#   iqr: 
#     run: r:latest analysis/iqr.R
#     needs: [generate_study_population]
#     outputs:
#       moderately_sensitive:
#         full: output/simplified_output/5_group/tables/range_fullset.csv
#         registered: output/simplified_output/5_group/tables/range_registered.csv    
#         figures: output/simplified_output/5_group/figures/density*.svg    

# ## Only to be run locally
#   generate_report:
#     run: python:latest jupyter nbconvert /workspace/notebooks_jupyter/draft_report_ethnicity.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
#     needs: [execute_simple_validation_analyses,execute_simple_validation_analyses_16]
#     outputs:
#       moderately_sensitive:
#         notebook: output/draft_report_ethnicity.html

#   local_simple_run:
#     run: python:latest python analysis/local_simple_run.py
#     outputs:
#       moderately_sensitive: 
#         tables: output/from_jobserver/release_2022_11_18/made_locally/*.csv

################## over time

  time_tables:
    run: r:latest analysis/time/times.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        data: output/time/*.csv
        plots: output/time/*.png