version: '3.0'

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input.feather

  generate_report_ethnicity:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks_jupyter/report_ethnicity_rp.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/report_ethnicity_rp.html
