version: '3.0'

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input.feather

  generate_tables:
    run: r:latest analysis/counts.r
    needs: [generate_study_population]
    outputs:      
      moderately_sensitive:
        table1: output/tables/full_SNOMED.rds
        table2: output/tables/full_ethnicity_compare.rds
        table3: output/tables/full_missing.rds
        table4: output/tables/full_missing_compare.rds
        table5: output/tables/reg_SNOMED.rds
        table6: output/tables/reg_ethnicity_compare.rds
        table7: output/tables/reg_missing.rds
        table8: output/tables/reg_missing_compare.rds

  rmd_report:
    run: r:latest -e 'rmarkdown::render("analysis/ethnicity.Rmd",  knit_root_dir = "/workspace",  output_dir = "/workspace/notebook", output_format = c("html_document","rmarkdown::github_document")   )'
    needs:
    - generate_tables

    outputs:
      moderately_sensitive:
        html: notebook/ethnicity.html
        md: notebook/ethnicity.md