version: '3.0'

expectations:
  population_size: 1000

actions:
  split_codelist:
    run: stata-mp:latest analysis/00_trim_snomed_codelist.do
    outputs:
      highly_sensitive:
        data1: codelists/group1.csv
        data2: codelists/group2.csv
        data3: codelists/group3.csv
        data4: codelists/group4.csv
        data5: codelists/group5.csv
        data6: codelists/group6.csv
        data7: codelists/group7.csv
        data8: codelists/group8.csv
        data9: codelists/group9.csv
        data10: codelists/group10.csv
      moderately_sensitive:
        log: logs/00_trim_snomed_codelist.log

  generate_cohort1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_cohort2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2
    outputs:
      highly_sensitive:
        cohort: output/input_2.csv
  
  generate_cohort3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_3
    outputs:
      highly_sensitive:
        cohort: output/input_3.csv

  generate_cohort4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_4
    outputs:
      highly_sensitive:
        cohort: output/input_4.csv

  generate_cohort5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_5
    outputs:
      highly_sensitive:
        cohort: output/input_5.csv

  generate_cohort6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_6
    outputs:
      highly_sensitive:
        cohort: output/input_6.csv

  generate_cohort7:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_7
    outputs:
      highly_sensitive:
        cohort: output/input_7.csv

  generate_cohort8:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_8
    outputs:
      highly_sensitive:
        cohort: output/input_8.csv

  generate_cohort9:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_9
    outputs:
      highly_sensitive:
        cohort: output/input_9.csv

  generate_cohort10:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_10
    outputs:
      highly_sensitive:
        cohort: output/input_10.csv

  initial_counts:
    run: stata-mp:latest analysis/01_describe_snomed_ethnicity.do
    needs: [generate_cohort1, generate_cohort2, generate_cohort3, generate_cohort4, generate_cohort5, generate_cohort6, generate_cohort7, generate_cohort8, generate_cohort9, generate_cohort10]
    outputs:      
      moderately_sensitive:
        log: logs/01_describe_snomed_ethnicity.log
        table: output/snomed_ethnicity_counts.csv

  categorize_ethnicity:
    run: stata-mp:latest analysis/02_attach_ethnicity_categories.do
    needs: [generate_cohort1, generate_cohort2, generate_cohort3, generate_cohort4, generate_cohort5, generate_cohort6, generate_cohort7, generate_cohort8, generate_cohort9, generate_cohort10, initial_counts]
    outputs:      
      moderately_sensitive:
        log: logs/02_attach_ethnicity_categories.log
        table: output/snomed_ethnicity_codelist_forupload_Oct19.csv
