version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort_ctv3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ctv3
    outputs:
      highly_sensitive:
        cohort: output/input_ctv3.csv

  ctv3_check:
    run: r:latest analysis/ctv3_check.r
    needs: [generate_cohort_ctv3]
    outputs:      
      moderately_sensitive:
        table_ctv3: output/tables/ctv3_check.csv
