version: '3.0'

expectations:
  population_size: 1000

actions:
  split_codelist:
    run: r:latest analysis/sus/00_trim_snomed_codelist_sus.r
    outputs:
      highly_sensitive:
        data: codelists/ethnicity_*.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sus --output-dir=output --output-format feather
    needs: [split_codelist]
    outputs:
      highly_sensitive:
        cohort: output/data/input_sus.feather

  generate_dataset_report:
    run: >
      dataset-report:v0.0.9
        --input-files output/data/input_sus.feather
        --output-dir output/data
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        dataset_report: output/data/input_sus.html

  execute_simple_validation_analyses:
    run: python:latest python analysis/sus/simple_validation_script_sus.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive: 
        tables: output/sus/simplified_output/5_group/tables/*.csv
  #      figures: output/sus/simplified_output/5_group/figures/*.png

