version: '3.0'

expectations:
  population_size: 1000

actions:
#   split_codelist:
#     run: r:latest analysis/00_trim_snomed_codelist.r
#     outputs:
#       highly_sensitive:
#         data1: codelists/group_1.csv
#         data2: codelists/group_2.csv
#         data3: codelists/group_3.csv
#         data4: codelists/group_4.csv
#         data5: codelists/group_5.csv
#         data6: codelists/group_6.csv
#         data7: codelists/group_7.csv
#         data8: codelists/group_8.csv
#         data9: codelists/group_9.csv
#         data10: codelists/group_10.csv
#         data11: codelists/group_11.csv

#   generate_cohort1:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input.csv

#   generate_cohort2:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_2
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_2.csv
  
#   generate_cohort3:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_3
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_3.csv

#   generate_cohort4:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_4
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_4.csv

#   generate_cohort5:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_5
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_5.csv

#   generate_cohort6:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_6
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_6.csv

#   generate_cohort7:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_7
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_7.csv

#   generate_cohort8:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_8
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_8.csv

#   generate_cohort9:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_9
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_9.csv

#   generate_cohort10:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_10
#     needs: [split_codelist]    
#     outputs:
#       highly_sensitive:
#         cohort: output/input_10.csv

#   generate_cohort11:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_11
#     needs: [split_codelist]
#     outputs:
#       highly_sensitive:
#         cohort: output/input_11.csv

#   initial_counts:
#     run: r:latest analysis/01_describe_snomed_ethnicity.r
#     needs: [split_codelist,generate_cohort1, generate_cohort2, generate_cohort3, generate_cohort4, generate_cohort5, generate_cohort6, generate_cohort7, generate_cohort8, generate_cohort9, generate_cohort10, generate_cohort11]
#     outputs:      
#       moderately_sensitive:
#         table: output/for_release/snomed_ethnicity_counts.csv
#         table_unredact: output/unredacted/snomed_ethnicity_counts.csv

  generate_cohort_ctv3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ctv3
    outputs:
      highly_sensitive:
        cohort: output/input_ctv3.csv

  initial_counts:
    run: r:latest analysis/ctv3_check.r
    needs: [generate_cohort_ctv3]
    outputs:      
      moderately_sensitive:
        table_ctv3: output/tables/ctv3_check.csv
